// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerOptions", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameCoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GameStatusId")
                        .HasColumnType("int");

                    b.Property<int>("HostId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<string>("RoomPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameStatusId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.GameComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameComments", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.GameResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfCorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfQuestions")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("GameResults");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GameStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GameStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Not started"
                        },
                        new
                        {
                            Id = 2,
                            Name = "In process"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Players", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameCoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Quizzes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameCoverImageUrl = "https://localhost:7292/covers/quiz_1.jpg",
                            GameName = "Мифология Древней Греции",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameCoverImageUrl = "https://localhost:7292/covers/quiz_2.jpg",
                            GameName = "Древний Рим",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameCoverImageUrl = "https://localhost:7292/covers/quiz_3.jpg",
                            GameName = "Современные технологии",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameCoverImageUrl = "https://localhost:7292/covers/quiz_4.jpg",
                            GameName = "Основы программирования",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameCoverImageUrl = "https://localhost:7292/covers/quiz_5.jpg",
                            GameName = "Продвинутое программирование",
                            StartTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizAnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId");

                    b.ToTable("QuizAnswerOptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = false,
                            QuizQuestionId = 1,
                            Text = "Посейдон"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuizQuestionId = 1,
                            Text = "Геракл"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = true,
                            QuizQuestionId = 1,
                            Text = "Зевс"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuizQuestionId = 1,
                            Text = "Аполлон"
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = false,
                            QuizQuestionId = 2,
                            Text = "Арес"
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = true,
                            QuizQuestionId = 2,
                            Text = "Гефест"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            QuizQuestionId = 2,
                            Text = "Аполлон"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            QuizQuestionId = 2,
                            Text = "Зевс"
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = false,
                            QuizQuestionId = 3,
                            Text = "Гермес"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = true,
                            QuizQuestionId = 3,
                            Text = "Посейдон"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = false,
                            QuizQuestionId = 3,
                            Text = "Дионис"
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = false,
                            QuizQuestionId = 3,
                            Text = "Афина"
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            QuizQuestionId = 4,
                            Text = "Гера"
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = true,
                            QuizQuestionId = 4,
                            Text = "Афина"
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = false,
                            QuizQuestionId = 4,
                            Text = "Артемида"
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            QuizQuestionId = 4,
                            Text = "Персефона"
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            QuizQuestionId = 5,
                            Text = "Гермес"
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = true,
                            QuizQuestionId = 5,
                            Text = "Арес"
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = false,
                            QuizQuestionId = 5,
                            Text = "Зевс"
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            QuizQuestionId = 5,
                            Text = "Аполлон"
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            QuizQuestionId = 6,
                            Text = "Гера"
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = true,
                            QuizQuestionId = 6,
                            Text = "Артемида"
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            QuizQuestionId = 6,
                            Text = "Афродита"
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = false,
                            QuizQuestionId = 6,
                            Text = "Афина"
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = true,
                            QuizQuestionId = 7,
                            Text = "Гермес"
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = false,
                            QuizQuestionId = 7,
                            Text = "Аполлон"
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            QuizQuestionId = 7,
                            Text = "Арес"
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = false,
                            QuizQuestionId = 7,
                            Text = "Дионис"
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = false,
                            QuizQuestionId = 8,
                            Text = "Арес"
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = true,
                            QuizQuestionId = 8,
                            Text = "Аполлон"
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = false,
                            QuizQuestionId = 8,
                            Text = "Зевс"
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            QuizQuestionId = 8,
                            Text = "Гермес"
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = false,
                            QuizQuestionId = 9,
                            Text = "Афина"
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            QuizQuestionId = 9,
                            Text = "Артемида"
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = true,
                            QuizQuestionId = 9,
                            Text = "Афродита"
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            QuizQuestionId = 9,
                            Text = "Гера"
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = false,
                            QuizQuestionId = 10,
                            Text = "Кронос"
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = false,
                            QuizQuestionId = 10,
                            Text = "Гиперион"
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = true,
                            QuizQuestionId = 10,
                            Text = "Атлас"
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = false,
                            QuizQuestionId = 10,
                            Text = "Гигант"
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = true,
                            QuizQuestionId = 11,
                            Text = "Ромул"
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            QuizQuestionId = 11,
                            Text = "Рем"
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            QuizQuestionId = 11,
                            Text = "Цезарь"
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = false,
                            QuizQuestionId = 11,
                            Text = "Август"
                        },
                        new
                        {
                            Id = 45,
                            IsCorrect = false,
                            QuizQuestionId = 12,
                            Text = "Нерон"
                        },
                        new
                        {
                            Id = 46,
                            IsCorrect = true,
                            QuizQuestionId = 12,
                            Text = "Август"
                        },
                        new
                        {
                            Id = 47,
                            IsCorrect = false,
                            QuizQuestionId = 12,
                            Text = "Тиберий"
                        },
                        new
                        {
                            Id = 48,
                            IsCorrect = false,
                            QuizQuestionId = 12,
                            Text = "Клавдий"
                        },
                        new
                        {
                            Id = 49,
                            IsCorrect = true,
                            QuizQuestionId = 13,
                            Text = "Юпитер"
                        },
                        new
                        {
                            Id = 50,
                            IsCorrect = false,
                            QuizQuestionId = 13,
                            Text = "Марс"
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = false,
                            QuizQuestionId = 13,
                            Text = "Венера"
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = false,
                            QuizQuestionId = 13,
                            Text = "Сатурн"
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = false,
                            QuizQuestionId = 14,
                            Text = "Панем"
                        },
                        new
                        {
                            Id = 54,
                            IsCorrect = false,
                            QuizQuestionId = 14,
                            Text = "Луперкалии"
                        },
                        new
                        {
                            Id = 55,
                            IsCorrect = true,
                            QuizQuestionId = 14,
                            Text = "Тритон"
                        },
                        new
                        {
                            Id = 56,
                            IsCorrect = false,
                            QuizQuestionId = 14,
                            Text = "Сатурналии"
                        },
                        new
                        {
                            Id = 57,
                            IsCorrect = true,
                            QuizQuestionId = 15,
                            Text = "Ганнибал"
                        },
                        new
                        {
                            Id = 58,
                            IsCorrect = false,
                            QuizQuestionId = 15,
                            Text = "Цезарь"
                        },
                        new
                        {
                            Id = 59,
                            IsCorrect = false,
                            QuizQuestionId = 15,
                            Text = "Октавиан"
                        },
                        new
                        {
                            Id = 60,
                            IsCorrect = false,
                            QuizQuestionId = 15,
                            Text = "Сципион"
                        },
                        new
                        {
                            Id = 61,
                            IsCorrect = true,
                            QuizQuestionId = 16,
                            Text = "Колизей"
                        },
                        new
                        {
                            Id = 62,
                            IsCorrect = false,
                            QuizQuestionId = 16,
                            Text = "Пантеон"
                        },
                        new
                        {
                            Id = 63,
                            IsCorrect = false,
                            QuizQuestionId = 16,
                            Text = "Форум"
                        },
                        new
                        {
                            Id = 64,
                            IsCorrect = false,
                            QuizQuestionId = 16,
                            Text = "Кирка"
                        },
                        new
                        {
                            Id = 65,
                            IsCorrect = true,
                            QuizQuestionId = 17,
                            Text = "Латинский"
                        },
                        new
                        {
                            Id = 66,
                            IsCorrect = false,
                            QuizQuestionId = 17,
                            Text = "Греческий"
                        },
                        new
                        {
                            Id = 67,
                            IsCorrect = false,
                            QuizQuestionId = 17,
                            Text = "Еврейский"
                        },
                        new
                        {
                            Id = 68,
                            IsCorrect = false,
                            QuizQuestionId = 17,
                            Text = "Арабский"
                        },
                        new
                        {
                            Id = 69,
                            IsCorrect = true,
                            QuizQuestionId = 18,
                            Text = "Архитектура"
                        },
                        new
                        {
                            Id = 70,
                            IsCorrect = false,
                            QuizQuestionId = 18,
                            Text = "Живопись"
                        },
                        new
                        {
                            Id = 71,
                            IsCorrect = false,
                            QuizQuestionId = 18,
                            Text = "Музыка"
                        },
                        new
                        {
                            Id = 72,
                            IsCorrect = false,
                            QuizQuestionId = 18,
                            Text = "Скульптура"
                        },
                        new
                        {
                            Id = 73,
                            IsCorrect = false,
                            QuizQuestionId = 19,
                            Text = "Монархия"
                        },
                        new
                        {
                            Id = 74,
                            IsCorrect = true,
                            QuizQuestionId = 19,
                            Text = "Республика"
                        },
                        new
                        {
                            Id = 75,
                            IsCorrect = false,
                            QuizQuestionId = 19,
                            Text = "Демократия"
                        },
                        new
                        {
                            Id = 76,
                            IsCorrect = false,
                            QuizQuestionId = 19,
                            Text = "Олигархия"
                        },
                        new
                        {
                            Id = 77,
                            IsCorrect = false,
                            QuizQuestionId = 20,
                            Text = "V веке до н.э."
                        },
                        new
                        {
                            Id = 78,
                            IsCorrect = true,
                            QuizQuestionId = 20,
                            Text = "IV веке н.э."
                        },
                        new
                        {
                            Id = 79,
                            IsCorrect = false,
                            QuizQuestionId = 20,
                            Text = "III веке до н.э."
                        },
                        new
                        {
                            Id = 80,
                            IsCorrect = false,
                            QuizQuestionId = 20,
                            Text = "I веке до н.э."
                        },
                        new
                        {
                            Id = 81,
                            IsCorrect = false,
                            QuizQuestionId = 21,
                            Text = "Ruby"
                        },
                        new
                        {
                            Id = 82,
                            IsCorrect = false,
                            QuizQuestionId = 21,
                            Text = "JavaScript"
                        },
                        new
                        {
                            Id = 83,
                            IsCorrect = true,
                            QuizQuestionId = 21,
                            Text = "Python"
                        },
                        new
                        {
                            Id = 84,
                            IsCorrect = false,
                            QuizQuestionId = 21,
                            Text = "Go"
                        },
                        new
                        {
                            Id = 85,
                            IsCorrect = true,
                            QuizQuestionId = 22,
                            Text = "GitHub"
                        },
                        new
                        {
                            Id = 86,
                            IsCorrect = false,
                            QuizQuestionId = 22,
                            Text = "Docker"
                        },
                        new
                        {
                            Id = 87,
                            IsCorrect = false,
                            QuizQuestionId = 22,
                            Text = "Google Drive"
                        },
                        new
                        {
                            Id = 88,
                            IsCorrect = false,
                            QuizQuestionId = 22,
                            Text = "Slack"
                        },
                        new
                        {
                            Id = 89,
                            IsCorrect = true,
                            QuizQuestionId = 23,
                            Text = "Apple"
                        },
                        new
                        {
                            Id = 90,
                            IsCorrect = false,
                            QuizQuestionId = 23,
                            Text = "Microsoft"
                        },
                        new
                        {
                            Id = 91,
                            IsCorrect = false,
                            QuizQuestionId = 23,
                            Text = "Google"
                        },
                        new
                        {
                            Id = 92,
                            IsCorrect = false,
                            QuizQuestionId = 23,
                            Text = "Amazon"
                        },
                        new
                        {
                            Id = 93,
                            IsCorrect = false,
                            QuizQuestionId = 24,
                            Text = "JavaScript"
                        },
                        new
                        {
                            Id = 94,
                            IsCorrect = false,
                            QuizQuestionId = 24,
                            Text = "Python"
                        },
                        new
                        {
                            Id = 95,
                            IsCorrect = true,
                            QuizQuestionId = 24,
                            Text = "PHP"
                        },
                        new
                        {
                            Id = 96,
                            IsCorrect = false,
                            QuizQuestionId = 24,
                            Text = "C++"
                        },
                        new
                        {
                            Id = 97,
                            IsCorrect = false,
                            QuizQuestionId = 25,
                            Text = "MySQL"
                        },
                        new
                        {
                            Id = 98,
                            IsCorrect = false,
                            QuizQuestionId = 25,
                            Text = "SQLite"
                        },
                        new
                        {
                            Id = 99,
                            IsCorrect = true,
                            QuizQuestionId = 25,
                            Text = "Hadoop"
                        },
                        new
                        {
                            Id = 100,
                            IsCorrect = false,
                            QuizQuestionId = 25,
                            Text = "Redis"
                        },
                        new
                        {
                            Id = 101,
                            IsCorrect = false,
                            QuizQuestionId = 26,
                            Text = "TCP"
                        },
                        new
                        {
                            Id = 102,
                            IsCorrect = false,
                            QuizQuestionId = 26,
                            Text = "UDP"
                        },
                        new
                        {
                            Id = 103,
                            IsCorrect = true,
                            QuizQuestionId = 26,
                            Text = "TLS"
                        },
                        new
                        {
                            Id = 104,
                            IsCorrect = false,
                            QuizQuestionId = 26,
                            Text = "FTP"
                        },
                        new
                        {
                            Id = 105,
                            IsCorrect = false,
                            QuizQuestionId = 27,
                            Text = "Angular"
                        },
                        new
                        {
                            Id = 106,
                            IsCorrect = false,
                            QuizQuestionId = 27,
                            Text = "Vue"
                        },
                        new
                        {
                            Id = 107,
                            IsCorrect = true,
                            QuizQuestionId = 27,
                            Text = "React"
                        },
                        new
                        {
                            Id = 108,
                            IsCorrect = false,
                            QuizQuestionId = 27,
                            Text = "Svelte"
                        },
                        new
                        {
                            Id = 109,
                            IsCorrect = false,
                            QuizQuestionId = 28,
                            Text = "Ruby"
                        },
                        new
                        {
                            Id = 110,
                            IsCorrect = false,
                            QuizQuestionId = 28,
                            Text = "JavaScript"
                        },
                        new
                        {
                            Id = 111,
                            IsCorrect = true,
                            QuizQuestionId = 28,
                            Text = "Python"
                        },
                        new
                        {
                            Id = 112,
                            IsCorrect = false,
                            QuizQuestionId = 28,
                            Text = "Go"
                        },
                        new
                        {
                            Id = 113,
                            IsCorrect = true,
                            QuizQuestionId = 29,
                            Text = "Vim"
                        },
                        new
                        {
                            Id = 114,
                            IsCorrect = false,
                            QuizQuestionId = 29,
                            Text = "Notepad"
                        },
                        new
                        {
                            Id = 115,
                            IsCorrect = false,
                            QuizQuestionId = 29,
                            Text = "Paint"
                        },
                        new
                        {
                            Id = 116,
                            IsCorrect = false,
                            QuizQuestionId = 29,
                            Text = "MS Word"
                        },
                        new
                        {
                            Id = 117,
                            IsCorrect = false,
                            QuizQuestionId = 30,
                            Text = "XML"
                        },
                        new
                        {
                            Id = 118,
                            IsCorrect = true,
                            QuizQuestionId = 30,
                            Text = "JSON"
                        },
                        new
                        {
                            Id = 119,
                            IsCorrect = false,
                            QuizQuestionId = 30,
                            Text = "HTML"
                        },
                        new
                        {
                            Id = 120,
                            IsCorrect = false,
                            QuizQuestionId = 30,
                            Text = "CSV"
                        },
                        new
                        {
                            Id = 121,
                            IsCorrect = false,
                            QuizQuestionId = 31,
                            Text = "Объект"
                        },
                        new
                        {
                            Id = 122,
                            IsCorrect = true,
                            QuizQuestionId = 31,
                            Text = "Память"
                        },
                        new
                        {
                            Id = 123,
                            IsCorrect = false,
                            QuizQuestionId = 31,
                            Text = "Код"
                        },
                        new
                        {
                            Id = 124,
                            IsCorrect = false,
                            QuizQuestionId = 31,
                            Text = "Тип"
                        },
                        new
                        {
                            Id = 125,
                            IsCorrect = true,
                            QuizQuestionId = 32,
                            Text = "Int"
                        },
                        new
                        {
                            Id = 126,
                            IsCorrect = false,
                            QuizQuestionId = 32,
                            Text = "String"
                        },
                        new
                        {
                            Id = 127,
                            IsCorrect = false,
                            QuizQuestionId = 32,
                            Text = "Bool"
                        },
                        new
                        {
                            Id = 128,
                            IsCorrect = false,
                            QuizQuestionId = 32,
                            Text = "Char"
                        },
                        new
                        {
                            Id = 129,
                            IsCorrect = true,
                            QuizQuestionId = 33,
                            Text = "Условие"
                        },
                        new
                        {
                            Id = 130,
                            IsCorrect = false,
                            QuizQuestionId = 33,
                            Text = "Цикл"
                        },
                        new
                        {
                            Id = 131,
                            IsCorrect = false,
                            QuizQuestionId = 33,
                            Text = "Метод"
                        },
                        new
                        {
                            Id = 132,
                            IsCorrect = false,
                            QuizQuestionId = 33,
                            Text = "Переменная"
                        },
                        new
                        {
                            Id = 133,
                            IsCorrect = true,
                            QuizQuestionId = 34,
                            Text = "[]"
                        },
                        new
                        {
                            Id = 134,
                            IsCorrect = false,
                            QuizQuestionId = 34,
                            Text = "{}"
                        },
                        new
                        {
                            Id = 135,
                            IsCorrect = false,
                            QuizQuestionId = 34,
                            Text = "()"
                        },
                        new
                        {
                            Id = 136,
                            IsCorrect = false,
                            QuizQuestionId = 34,
                            Text = "<>"
                        },
                        new
                        {
                            Id = 137,
                            IsCorrect = true,
                            QuizQuestionId = 35,
                            Text = "Повтор"
                        },
                        new
                        {
                            Id = 138,
                            IsCorrect = false,
                            QuizQuestionId = 35,
                            Text = "Условие"
                        },
                        new
                        {
                            Id = 139,
                            IsCorrect = false,
                            QuizQuestionId = 35,
                            Text = "Класс"
                        },
                        new
                        {
                            Id = 140,
                            IsCorrect = false,
                            QuizQuestionId = 35,
                            Text = "Массив"
                        },
                        new
                        {
                            Id = 141,
                            IsCorrect = true,
                            QuizQuestionId = 36,
                            Text = "WriteLine"
                        },
                        new
                        {
                            Id = 142,
                            IsCorrect = false,
                            QuizQuestionId = 36,
                            Text = "ReadLine"
                        },
                        new
                        {
                            Id = 143,
                            IsCorrect = false,
                            QuizQuestionId = 36,
                            Text = "Print"
                        },
                        new
                        {
                            Id = 144,
                            IsCorrect = false,
                            QuizQuestionId = 36,
                            Text = "Log"
                        },
                        new
                        {
                            Id = 145,
                            IsCorrect = true,
                            QuizQuestionId = 37,
                            Text = "Без объекта"
                        },
                        new
                        {
                            Id = 146,
                            IsCorrect = false,
                            QuizQuestionId = 37,
                            Text = "Общедоступный"
                        },
                        new
                        {
                            Id = 147,
                            IsCorrect = false,
                            QuizQuestionId = 37,
                            Text = "Изменяемый"
                        },
                        new
                        {
                            Id = 148,
                            IsCorrect = false,
                            QuizQuestionId = 37,
                            Text = "Скрытый"
                        },
                        new
                        {
                            Id = 149,
                            IsCorrect = true,
                            QuizQuestionId = 38,
                            Text = "C"
                        },
                        new
                        {
                            Id = 150,
                            IsCorrect = false,
                            QuizQuestionId = 38,
                            Text = "Java"
                        },
                        new
                        {
                            Id = 151,
                            IsCorrect = false,
                            QuizQuestionId = 38,
                            Text = "C#"
                        },
                        new
                        {
                            Id = 152,
                            IsCorrect = false,
                            QuizQuestionId = 38,
                            Text = "Python"
                        },
                        new
                        {
                            Id = 153,
                            IsCorrect = true,
                            QuizQuestionId = 39,
                            Text = "Функция"
                        },
                        new
                        {
                            Id = 154,
                            IsCorrect = false,
                            QuizQuestionId = 39,
                            Text = "Класс"
                        },
                        new
                        {
                            Id = 155,
                            IsCorrect = false,
                            QuizQuestionId = 39,
                            Text = "Цикл"
                        },
                        new
                        {
                            Id = 156,
                            IsCorrect = false,
                            QuizQuestionId = 39,
                            Text = "Переменная"
                        },
                        new
                        {
                            Id = 157,
                            IsCorrect = true,
                            QuizQuestionId = 40,
                            Text = "=="
                        },
                        new
                        {
                            Id = 158,
                            IsCorrect = false,
                            QuizQuestionId = 40,
                            Text = "="
                        },
                        new
                        {
                            Id = 159,
                            IsCorrect = false,
                            QuizQuestionId = 40,
                            Text = "!="
                        },
                        new
                        {
                            Id = 160,
                            IsCorrect = false,
                            QuizQuestionId = 40,
                            Text = "<>"
                        },
                        new
                        {
                            Id = 161,
                            IsCorrect = true,
                            QuizQuestionId = 41,
                            Text = "new"
                        },
                        new
                        {
                            Id = 162,
                            IsCorrect = false,
                            QuizQuestionId = 41,
                            Text = "var"
                        },
                        new
                        {
                            Id = 163,
                            IsCorrect = false,
                            QuizQuestionId = 41,
                            Text = "class"
                        },
                        new
                        {
                            Id = 164,
                            IsCorrect = false,
                            QuizQuestionId = 41,
                            Text = "using"
                        },
                        new
                        {
                            Id = 165,
                            IsCorrect = true,
                            QuizQuestionId = 42,
                            Text = "Инкапсуляция"
                        },
                        new
                        {
                            Id = 166,
                            IsCorrect = false,
                            QuizQuestionId = 42,
                            Text = "Наследование"
                        },
                        new
                        {
                            Id = 167,
                            IsCorrect = false,
                            QuizQuestionId = 42,
                            Text = "Полиморфизм"
                        },
                        new
                        {
                            Id = 168,
                            IsCorrect = false,
                            QuizQuestionId = 42,
                            Text = "Абстракция"
                        },
                        new
                        {
                            Id = 169,
                            IsCorrect = true,
                            QuizQuestionId = 43,
                            Text = "void"
                        },
                        new
                        {
                            Id = 170,
                            IsCorrect = false,
                            QuizQuestionId = 43,
                            Text = "null"
                        },
                        new
                        {
                            Id = 171,
                            IsCorrect = false,
                            QuizQuestionId = 43,
                            Text = "object"
                        },
                        new
                        {
                            Id = 172,
                            IsCorrect = false,
                            QuizQuestionId = 43,
                            Text = "int"
                        },
                        new
                        {
                            Id = 173,
                            IsCorrect = true,
                            QuizQuestionId = 44,
                            Text = "Object"
                        },
                        new
                        {
                            Id = 174,
                            IsCorrect = false,
                            QuizQuestionId = 44,
                            Text = "Base"
                        },
                        new
                        {
                            Id = 175,
                            IsCorrect = false,
                            QuizQuestionId = 44,
                            Text = "System"
                        },
                        new
                        {
                            Id = 176,
                            IsCorrect = false,
                            QuizQuestionId = 44,
                            Text = "Root"
                        },
                        new
                        {
                            Id = 177,
                            IsCorrect = true,
                            QuizQuestionId = 45,
                            Text = "&&"
                        },
                        new
                        {
                            Id = 178,
                            IsCorrect = false,
                            QuizQuestionId = 45,
                            Text = "&"
                        },
                        new
                        {
                            Id = 179,
                            IsCorrect = false,
                            QuizQuestionId = 45,
                            Text = "||"
                        },
                        new
                        {
                            Id = 180,
                            IsCorrect = false,
                            QuizQuestionId = 45,
                            Text = "!"
                        },
                        new
                        {
                            Id = 181,
                            IsCorrect = true,
                            QuizQuestionId = 46,
                            Text = "Переопределение"
                        },
                        new
                        {
                            Id = 182,
                            IsCorrect = false,
                            QuizQuestionId = 46,
                            Text = "Наследование"
                        },
                        new
                        {
                            Id = 183,
                            IsCorrect = false,
                            QuizQuestionId = 46,
                            Text = "Инкапсуляция"
                        },
                        new
                        {
                            Id = 184,
                            IsCorrect = false,
                            QuizQuestionId = 46,
                            Text = "Абстракция"
                        },
                        new
                        {
                            Id = 185,
                            IsCorrect = true,
                            QuizQuestionId = 47,
                            Text = "Конструктор"
                        },
                        new
                        {
                            Id = 186,
                            IsCorrect = false,
                            QuizQuestionId = 47,
                            Text = "Деструктор"
                        },
                        new
                        {
                            Id = 187,
                            IsCorrect = false,
                            QuizQuestionId = 47,
                            Text = "Метод"
                        },
                        new
                        {
                            Id = 188,
                            IsCorrect = false,
                            QuizQuestionId = 47,
                            Text = "Класс"
                        },
                        new
                        {
                            Id = 189,
                            IsCorrect = true,
                            QuizQuestionId = 48,
                            Text = "string"
                        },
                        new
                        {
                            Id = 190,
                            IsCorrect = false,
                            QuizQuestionId = 48,
                            Text = "char"
                        },
                        new
                        {
                            Id = 191,
                            IsCorrect = false,
                            QuizQuestionId = 48,
                            Text = "text"
                        },
                        new
                        {
                            Id = 192,
                            IsCorrect = false,
                            QuizQuestionId = 48,
                            Text = "var"
                        },
                        new
                        {
                            Id = 193,
                            IsCorrect = true,
                            QuizQuestionId = 49,
                            Text = "Exit"
                        },
                        new
                        {
                            Id = 194,
                            IsCorrect = false,
                            QuizQuestionId = 49,
                            Text = "Close"
                        },
                        new
                        {
                            Id = 195,
                            IsCorrect = false,
                            QuizQuestionId = 49,
                            Text = "End"
                        },
                        new
                        {
                            Id = 196,
                            IsCorrect = false,
                            QuizQuestionId = 49,
                            Text = "Return"
                        },
                        new
                        {
                            Id = 197,
                            IsCorrect = true,
                            QuizQuestionId = 50,
                            Text = "Exception"
                        },
                        new
                        {
                            Id = 198,
                            IsCorrect = false,
                            QuizQuestionId = 50,
                            Text = "Error"
                        },
                        new
                        {
                            Id = 199,
                            IsCorrect = false,
                            QuizQuestionId = 50,
                            Text = "Bug"
                        },
                        new
                        {
                            Id = 200,
                            IsCorrect = false,
                            QuizQuestionId = 50,
                            Text = "Crash"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizComments", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("QuizQuestionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был верховным богом в греческой мифологии?"
                        },
                        new
                        {
                            Id = 2,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Какой бог был покровителем кузнецов и огня?"
                        },
                        new
                        {
                            Id = 3,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был богом моря?"
                        },
                        new
                        {
                            Id = 4,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был богиней мудрости?"
                        },
                        new
                        {
                            Id = 5,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был богом войны?"
                        },
                        new
                        {
                            Id = 6,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был богиней охоты?"
                        },
                        new
                        {
                            Id = 7,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был вестником богов?"
                        },
                        new
                        {
                            Id = 8,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был богом солнца?"
                        },
                        new
                        {
                            Id = 9,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был богиней любви и красоты?"
                        },
                        new
                        {
                            Id = 10,
                            QuizId = 1,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был титаном, держащим небо на своих плечах?"
                        },
                        new
                        {
                            Id = 11,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был основателем Рима?"
                        },
                        new
                        {
                            Id = 12,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Какой был последний император Рима?"
                        },
                        new
                        {
                            Id = 13,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Какой бог был покровителем Рима?"
                        },
                        new
                        {
                            Id = 14,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Какой праздник был посвящен славе императоров?"
                        },
                        new
                        {
                            Id = 15,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Кто был великим полководцем Рима?"
                        },
                        new
                        {
                            Id = 16,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Какое здание является символом Рима?"
                        },
                        new
                        {
                            Id = 17,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Какой язык был официальным в Риме?"
                        },
                        new
                        {
                            Id = 18,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Какое искусство было популярно в Риме?"
                        },
                        new
                        {
                            Id = 19,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Какой строй был установлен в Риме?"
                        },
                        new
                        {
                            Id = 20,
                            QuizId = 2,
                            QuizQuestionImageUrl = "",
                            Text = "Какой век считается временем расцвета Рима?"
                        },
                        new
                        {
                            Id = 21,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Какой язык программирования чаще всего используется для создания машинного обучения?"
                        },
                        new
                        {
                            Id = 22,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Какой сервис используется для хранения проектов с контролем версий?"
                        },
                        new
                        {
                            Id = 23,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Какая компания разработала язык Swift?"
                        },
                        new
                        {
                            Id = 24,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Какой язык программирования чаще всего используется для веб-разработки на серверной стороне?"
                        },
                        new
                        {
                            Id = 25,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Какая система управления базами данных является популярной для больших данных?"
                        },
                        new
                        {
                            Id = 26,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Какой протокол используется для защиты данных при передаче в интернете?"
                        },
                        new
                        {
                            Id = 27,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Как называется популярный фреймворк для фронтенд-разработки от Facebook?"
                        },
                        new
                        {
                            Id = 28,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Какой язык программирования чаще всего используется для создания машинного обучения?"
                        },
                        new
                        {
                            Id = 29,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Какой текстовый редактор стал популярным благодаря расширяемости и множеству плагинов?"
                        },
                        new
                        {
                            Id = 30,
                            QuizId = 3,
                            QuizQuestionImageUrl = "",
                            Text = "Как называется формат обмена данными, основанный на ключ-значение и часто используемый в API?"
                        },
                        new
                        {
                            Id = 31,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Что такое переменная?"
                        },
                        new
                        {
                            Id = 32,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Тип для чисел?"
                        },
                        new
                        {
                            Id = 33,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Что делает 'if'?"
                        },
                        new
                        {
                            Id = 34,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Как обозначается массив?"
                        },
                        new
                        {
                            Id = 35,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Что такое цикл?"
                        },
                        new
                        {
                            Id = 36,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Метод вывода?"
                        },
                        new
                        {
                            Id = 37,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Значение 'static'?"
                        },
                        new
                        {
                            Id = 38,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Не ООП язык?"
                        },
                        new
                        {
                            Id = 39,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Что такое метод?"
                        },
                        new
                        {
                            Id = 40,
                            QuizId = 4,
                            QuizQuestionImageUrl = "",
                            Text = "Оператор равенства?"
                        },
                        new
                        {
                            Id = 41,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Какой ключевое слово используется для создания объекта?"
                        },
                        new
                        {
                            Id = 42,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Как называется способ скрытия данных внутри класса?"
                        },
                        new
                        {
                            Id = 43,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Что возвращает метод без возвращаемого значения?"
                        },
                        new
                        {
                            Id = 44,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Как называется базовый класс всех типов в C#?"
                        },
                        new
                        {
                            Id = 45,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Какой оператор используется для логического И?"
                        },
                        new
                        {
                            Id = 46,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Как называется процесс выполнения метода с тем же именем в дочернем классе?"
                        },
                        new
                        {
                            Id = 47,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Какой метод вызывается при создании объекта?"
                        },
                        new
                        {
                            Id = 48,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Какой тип данных используется для хранения текста?"
                        },
                        new
                        {
                            Id = 49,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Какой метод используется для завершения программы?"
                        },
                        new
                        {
                            Id = 50,
                            QuizId = 5,
                            QuizQuestionImageUrl = "",
                            Text = "Как называется ошибка времени выполнения?"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReplay")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfCorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfQuestions")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId");

                    b.ToTable("QuizResults", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "paaworker@gmail.com",
                            FirstName = "Main",
                            IsActive = true,
                            IsAdmin = true,
                            IsEmailVerified = true,
                            LastName = "Admin",
                            Password = "$2a$11$9Y6i/HQgs1KnlFg6L29sI.SB3/HMIJ.zbZGrBg.8F9xTF6iHQblv6",
                            ProfileImageUrl = "https://localhost:7292/covers/1.jpg",
                            Username = "administrator"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Achievement")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarsSet")
                        .HasColumnType("int");

                    b.Property<int>("GameComments")
                        .HasColumnType("int");

                    b.Property<int>("GameCreated")
                        .HasColumnType("int");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("int");

                    b.Property<int>("ProfileEdits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("QuestionsCreated")
                        .HasColumnType("int");

                    b.Property<int>("QuizComments")
                        .HasColumnType("int");

                    b.Property<int>("QuizzesCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("QuizzesCreated")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserStatistics", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Models.AnswerOption", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Question", "Question")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Game", b =>
                {
                    b.HasOne("DataAccessLayer.Models.GameStatus", "Status")
                        .WithMany("Games")
                        .HasForeignKey("GameStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GameComment", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GameResults", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Game", "Game")
                        .WithMany("GameResults")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("GameResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Notification", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Player", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Question", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Game", "Game")
                        .WithMany("Questions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizAnswerOption", b =>
                {
                    b.HasOne("DataAccessLayer.Models.QuizQuestion", "QuizQuestion")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizComment", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Quiz", "Quiz")
                        .WithMany("Comments")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizQuestion", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizResults", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Quiz", "Quiz")
                        .WithMany("QuizResults")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("QuizResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserAchievement", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserStatistics", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", "User")
                        .WithOne("Statistics")
                        .HasForeignKey("DataAccessLayer.Models.UserStatistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Game", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("GameResults");

                    b.Navigation("Players");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.GameStatus", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Question", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Quiz", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Questions");

                    b.Navigation("QuizResults");
                });

            modelBuilder.Entity("DataAccessLayer.Models.QuizQuestion", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("GameResults");

                    b.Navigation("Notifications");

                    b.Navigation("QuizResults");

                    b.Navigation("Statistics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
